//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 49,00	22,65	0,000000075	-0,000000349	-0,0942
        ///49,00	22,66	0,000000076	-0,000000347	-0,0940
        ///49,00	22,67	0,000000076	-0,000000344	-0,0939
        ///49,00	22,68	0,000000077	-0,000000342	-0,0937
        ///49,00	22,69	0,000000078	-0,000000339	-0,0936
        ///49,00	22,70	0,000000078	-0,000000337	-0,0935
        ///49,00	22,71	0,000000079	-0,000000336	-0,0933
        ///49,00	22,74	0,000000081	-0,000000326	-0,0931
        ///49,00	22,75	0,000000082	-0,000000325	-0,0931
        ///49,00	22,76	0,000000083	-0,000000321	-0,0930
        ///49,00	22,77	0,000000085	-0,000000318	-0,0931
        ///49,00	 [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string Grid {
            get {
                return ResourceManager.GetString("Grid", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 49,00	22,65	0,000000075	-0,000000349	-0,0942
        ///49,00	22,66	0,000000076	-0,000000347	-0,0940
        ///49,00	22,67	0,000000076	-0,000000344	-0,0939
        ///49,00	22,68	0,000000077	-0,000000342	-0,0937
        ///49,00	22,69	0,000000078	-0,000000339	-0,0936
        ///49,00	22,70	0,000000078	-0,000000337	-0,0935
        ///49,00	22,71	0,000000079	-0,000000336	-0,0933
        ///49,00	22,74	0,000000081	-0,000000326	-0,0931
        ///49,00	22,75	0,000000082	-0,000000325	-0,0931
        ///49,00	22,76	0,000000083	-0,000000321	-0,0930
        ///49,00	22,77	0,000000085	-0,000000318	-0,0931
        ///49,00	 [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string gridETRF {
            get {
                return ResourceManager.GetString("gridETRF", resourceCulture);
            }
        }
    }
}
